sudo: required

language: php

php:
  - 7.0
  - 7.1

before_install:
  - sudo apt-get -y install git zip php5-cli php5-curl

before_script:
  - composer self-update
  - composer install

script: vendor/bin/phpunit
