sudo: required

language: php

php:
  - 7.1

before_install:
  - sudo apt-get update
  - sudo apt-get install libcurl4-openssl-dev

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit
