sudo: required

language: php

php:
 - nightly

dist: trusty

os: linux

before_install:
  - sudo apt-get -y install git zip php5-cli php5-curl

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit
