sudo: false

language: php

php:
 - nightly
 - 7.0
 - hhvm

dist: trusty

os: linux

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit
